[0m[[0minfo[0m] [0mRunning tutorial.webapp.TutorialApp[0m
[0m[[0mdebug[0m] [0mwith JSEnv ExternalJSEnv for Node.js[0m
[0m[[0mdebug[0m] [0mStarting process: node[0m
[0m[[31merror[0m] [0mTypeError: Cannot read property 'body' of undefined[0m
[0m[[31merror[0m] [0m    at $c_Ltutorial_webapp_TutorialApp$.main__V (/home/ubuntu/workspace/scalajs/target/scala-2.11/file:/home/ubuntu/workspace/scalajs/app.scala:18:13)[0m
[0m[[31merror[0m] [0m    at $c_Ltutorial_webapp_TutorialApp$.$$js$exported$meth$main__O (/home/ubuntu/workspace/scalajs/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.13/library/src/main/scala/scala/scalajs/js/JSApp.scala:18:4)[0m
[0m[[31merror[0m] [0m    at $c_Ltutorial_webapp_TutorialApp$.main (/home/ubuntu/workspace/scalajs/target/scala-2.11/file:/home/ubuntu/workspace/scalajs/app.scala:7:8)[0m
[0m[[31merror[0m] [0m    at [stdin]:40:95[0m
[0m[[31merror[0m] [0m    at Object.exports.runInThisContext (vm.js:54:17)[0m
[0m[[31merror[0m] [0m    at Object.<anonymous> ([stdin]-wrapper:6:22)[0m
[0m[[31merror[0m] [0m    at Module._compile (module.js:409:26)[0m
[0m[[31merror[0m] [0m    at node.js:579:27[0m
[0m[[31merror[0m] [0m    at nextTickCallbackWith0Args (node.js:420:9)[0m
[0m[[31merror[0m] [0m    at process._tickCallback (node.js:349:13)[0m
org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:107)
	at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:156)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:684)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$60$$anonfun$apply$43$$anonfun$apply$44.apply(ScalaJSPluginInternal.scala:771)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$60$$anonfun$apply$43$$anonfun$apply$44.apply(ScalaJSPluginInternal.scala:765)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[0m[[31merror[0m] [0m(compile:[31mrun[0m) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1[0m
